#!/bin/bash

###########
##Single pathway analysis
##Input: $1 -- File name containting the SNP list
##
##Requires: up_pro.bed file -- contains the SNP reference information, generated by Plink
##                            plink2 --file hapmap3 --extract totalids.txt --keep CEU_hapmap --indep-pairwise 50 5 0.2 --r2 inter-chr with-freqs --ld-window-r2 0 --out uppro
##
##          metacca.db -- sqlite3 database with table snp_traits contains snp and trait information. Each row represents a snp, each column represnts a trait.
##
##Output: two files named with input file name and "r1", "r2" as postfix. "r1" contains the CCA coefficient and -log(p-value) of each SNP; "r2" contains the the CCA coefficient and -log(p-value) of the pathway.
############

KEGG_f=$1
KEGG_n=${KEGG_f%$".txt"}
echo $KEGG_n
cd /extra/xc/metacca

mkdir -p ld

if [[ ! -f result/$KEGG_n"_r1.txt" || ! -f result/$KEGG_n"_r2.txt"   ]];then
  if [ ! -f ld/$KEGG_n".ld" ];then
        plink2 --silent --bfile up_pro --extract pathway_checked/$KEGG_f --r2 inter-chr --ld-window-r2 0 --out ld/$KEGG_n
  fi

  mkdir -p input
  cd input

  echo "Prepare S_XX..."
  KEGG_snp=$KEGG_n"_snpid.txt"
  if [[  ! -f $KEGG_snp  ||  ! -f $KEGG_n"_XX.txt"  ]];then
        Rscript --no-save ../bin/vec_to_matrix.R $KEGG_n
  fi
  echo "Prepare S_XY..."
  sqlite3 ../metacca.db "drop table if exists snp_l_$KEGG_n"
  sqlite3 ../metacca.db "create table snp_l_$KEGG_n (snp_n varchar(20))"
  sqlite3 ../metacca.db ".import $KEGG_snp snp_l_$KEGG_n"
  sqlite3 ../metacca.db "select b.* from snp_l_$KEGG_n a, snp_traits b where a.snp_n=b.SNP" | cut -f2-16 -d"|" > $KEGG_n"_XY.txt"
  sqlite3 ../metacca.db "drop table snp_l_$KEGG_n"
  echo "metaCCA..."
  mkdir -p result
  Rscript --no-save ../bin/metaCCA.r $KEGG_n
fi

echo "DONE."
